webapp:
  container_name: jenkins
  build: .
  ports:
    - "80:8080"
  volumes:
    - /var/jenkins_home

nginx:
  container_name: nginx
  build: ./nginx
  ports:
    - "80:80"
  environment:
    - APP_PORT=8080