version: '2'
services:
  webapp:
    container_name: jenkins
    build: .
    volumes:
      - /var/jenkins_home

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
    environment:
      USERNAME: $USERNAME
      PASSWORD: $PASSWORD